# 1) Les chaines de caractères

In [21]:
nom= '151515151'
print(nom)

Joseph


In [4]:
score = 100
print(score)

100


In [5]:
# Ecrire sur plusieurs ligne


In [6]:
# Methode 1

In [7]:
texte_1 = 'Ici nous avons 2 filière : \n Informatique et telecom \n Ok ?'
print(texte_1)

Ici nous avons 2 filière : 
 Informatique et telecom 
 Ok ?


In [11]:
# Méthode 2
texte_2 = '''Ici nous avons 2 filière : Informatique et telecom Ok ? '''

print(texte_2)

# Les listes

In [12]:
# les listes vides

In [13]:
list_1 = []
print(list_1)

[]


In [30]:
# liste de trois prénom
list_2  = ['Regis', 'Anatole' , 'Antelme']
print(list_2)

['Regis', 'Anatole', 'Antelme']


In [31]:
# Afficher le premier élément de list_2
print(list_2[0])

Regis


In [34]:
# afficher la taille d'une liste
print(len(list_2))

4


In [33]:
# ajouter un élément à la fin d'une liste
list_2.append('Oscar')
print(list_2)

['Regis', 'Anatole', 'Antelme', 'Oscar']


In [37]:
# ajouter un élément suivant la position
list_2.insert(0,'Gaston')
print(list_2)
list_2.insert(2,'Jonas')
print(list_2)

['Gaston', 'Regis', 'Anatole', 'Antelme', 'Oscar']
['Gaston', 'Regis', 'Jonas', 'Anatole', 'Antelme', 'Oscar']


# Les fonctions

In [38]:
def maFonction() :
    print('je suis au cours')
    
    
# exécution

maFonction()

je suis au cours


# Structure de controles (les boucles)



In [41]:
# la boucle for

def ajout() :
    for i in range(0,20):
        print(i+2)
        
        
# exécution de la fonction

ajout()

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [43]:
def table4() :
    for a in range (0,13):
        calcul = 4 * a
        print('4 x ' + str(a) + '=' + str (calcul) )
        
# exécution
table4()

4 x 0=0
4 x 1=4
4 x 2=8
4 x 3=12
4 x 4=16
4 x 5=20
4 x 6=24
4 x 7=28
4 x 8=32
4 x 9=36
4 x 10=40
4 x 11=44
4 x 12=48


# Les dictionnaires python


In [2]:
list_dict = []

dico = {'nom' : 'Tony' , 'ecole' : 'Faucon' , 'niveau' : 'CM1'}

list_dict.append(dico)

dico = {'nom' : 'Toto' , 'ecole' : 'les genies' , 'niveau' : 'CP'}

list_dict.append(dico)

dico = {'nom' : 'Patou' , 'ecole' : 'Academy' , 'niveau' : 'CM1'}

list_dict.append(dico)

dico = {'nom' : 'Koffi' , 'ecole' : 'Faucon' , 'niveau' : 'CE2'}

list_dict.append(dico)

dico = {'nom' : 'Léo' , 'ecole' : 'Academy' , 'niveau' : 'CP'}

list_dict.append(dico)

dico = {'nom' : 'Les genies' , 'ecole' : 'les genies' , 'niveau' : 'CE'}

list_dict.append(dico)

dico = {'nom' : 'Patrice' , 'ecole' : 'Faucon' , 'niveau' : 'CM1'}

list_dict.append(dico)


print (list_dict)

[{'nom': 'Tony', 'ecole': 'Faucon', 'niveau': 'CM1'}, {'nom': 'Toto', 'ecole': 'les genies', 'niveau': 'CP'}, {'nom': 'Patou', 'ecole': 'Academy', 'niveau': 'CM1'}, {'nom': 'Koffi', 'ecole': 'Faucon', 'niveau': 'CE2'}, {'nom': 'Léo', 'ecole': 'Academy', 'niveau': 'CP'}, {'nom': 'Les genies', 'ecole': 'les genies', 'niveau': 'CE'}, {'nom': 'Patrice', 'ecole': 'Faucon', 'niveau': 'CM1'}]


In [13]:
def eleveCM1 () :
    
    for k in list_dict :
        
        if k["ecole"]=="Faucon" and k["niveau"] == "CM1":
            
            print(k["nom"])
            
            
eleveCM1()

Tony
Patrice




# Classe

### Attribut







classe avec attribut static

class Personne :
    
    def __init__(self) :
        self.nom = 'Dupont'
        self.prenom = 'Rogers'
        self.age = 31
        self.ville = 'Calavi'

In [16]:
eleve = Personne()

In [17]:
print (eleve.nom, eleve.prenom, eleve.age, eleve.ville)

Dupont Rogers 31 Calavi


In [19]:
etudiant = Individu (nom = 'Bako' , prenom = 'Roger')

print (etudiant.nom, etudiant.prenom)

Bako Roger


### Méthode 


In [21]:
class Vecteur :
    
    def __init__(self, x ,y) :
        
        self.x = x 
        self.y = y
        
        
    def somme (self) :
        
        calcul = self.x + self.y 
        
        return calcul

In [24]:
# creation de l'objet vecteur

u = Vecteur(x = 1 , y=-1 )

In [25]:
print(u.somme())

0


In [29]:

import numpy as np



# creation de nombre ou tableau de dimension 0 

arr = np.array(42)


print(arr)

# creation de nombre ou tableau de dimension 1
# contient des tableau de dimension 0

arr = np.array ([1,2,3,4,5])

print(arr)


# créer un dimension 2 
# contient des tableaux de dimensions 1

arr = np.array ([
    [1,2,5],
    [3,5,7],
    [8,5,6]
])


print(arr)

# créer un tableau de dimension 3


arr = np.array ([
    [
        [1,2,3],
        
        [4,5,6]
    ],
    
    [
        [7,5,3],
        
        [4,5,9]
    ],
])


print(arr)




42
[1 2 3 4 5]
[[1 2 5]
 [3 5 7]
 [8 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 5 3]
  [4 5 9]]]


In [30]:
# dimenesions d'un table

arr.ndim

3

In [31]:
# indexation

# accéder aux éléments d'un tableau

arr = np.array([43,22,1,10])

print(arr[0])

43
